GET http://localhost:8080/response
Accept: application/json

###

GET http://3.9.172.69:8080/actuator/health
Accept: application/json

###
GET http://3.9.172.69:8080/response
Accept: application/json

###

GET cf-fa-Publi-RO4UU8PFFFQI-1378699209.eu-west-2.elb.amazonaws.com:8080/response
Accept: application/json

###

GET cf-fa-Publi-RO4UU8PFFFQI-1378699209.eu-west-2.elb.amazonaws.com:8080/actuator/health
Accept: application/json

###

